server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  server:
    response-cache-update-interval-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    prefer-ip-address: true