apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discovery-service.fullname" . }}
  labels: {{- include "discovery-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "discovery-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "discovery-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "discovery-service.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springApplication.profiles }}
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "{{ .Values.eureka.server.enableSelfPreservation }}"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}