apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-service.fullname" . }}
  labels: {{- include "discovery-service.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30001
  selector: {{- include "discovery-service.selectorLabels" . | nindent 4 }}