spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      refresh:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 2    # Poll registry every 5 seconds
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2  # Send heartbeats every 5 seconds
    lease-expiration-duration-in-seconds: 4  # Consider service down after 10 seconds