spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_user
    username: postgres
    password: thaitoan2311
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration

log4j:
  logger:
    org:
      hibernate:
        SQL: debug

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
    com:
      taskify: DEBUG

# Server Configuration
server:
  port: 8081

# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/