spring:
  application:
    name: project-service

  # PostgreSQL Configuration
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5432/task_project
      username: postgres
      password: thaitoan2311

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: taskify


# Logging Configuration
logging:
  level:
    root: INFO
    com:
      taskify: DEBUG
    org:
      hibernate:
        SQL: DEBUG

log4j:
  logger:
    org:
      hibernate:
        SQL: debug

# Server Configuration
server:
  port: 8082

# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/