spring:
  application:
    name: iam-service
  config:
    import: optional:configserver:http://localhost:8888
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: thaitoan2311
  data:
    neo4j:
      database: iam-service
  # Add these properties to the iam-service.yml file
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
  health:
    diskspace:
      enabled: false
    db:
      enabled: false
    redis:
      enabled: false

rabbitmq:
  exchange:
    user-events: taskify.user.events
    membership-events: taskify.membership.events
  queue:
    iam-user-created-events: taskify.user-created.events.iam
    iam-user-deleted-events: taskify.user-updated.events.iam
    iam-membership-added-events: taskify.membership-added.events.iam
    iam-membership-removed-events: taskify.membership-removed.events.iam
    iam-membership-role-updated-events: taskify.membership-role-updated.events.iam