spring:
  application:
    name: organization-service
  config:
    import: optional:configserver:http://localhost:8888

services:
  iam:
    name: iam-service
    url: lb://iam-service


resilience4j:
  circuitbreaker:
    instances:
      iam-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5